source: ./public
destination: ./_site

web_path: /KitchenSink

exclude: [node_modules, vendor, grunt-tasks, Gruntfile.js, package.json, grunt-tasks, README.md, _site/**/*, tests, src, _less]

brand-name: ngKitchenSink
